---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productpage-svc-entry 
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - redhat.com
  ports:
  - number: 443
    name: https
    protocol: HTTPS 
  location: MESH_EXTERNAL
---