---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.control_plane_namespace }}
spec:
  selector:
    app: {{ .Values.ingress }} 
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP 
    hosts:
      - "{{ .Values.route_hostname }}"
