apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nonsso-api
spec:
  port:
    targetPort: http2
  tls:
    termination: edge
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  wildcardPolicy: None