
apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: {{ .Values.control_plane_name }}
spec:
  version: v2.0
  security:
    dataPlane:
      mtls: true
      automtls: true
    controlPlane:
      mtls: true
  runtime:
    components:
      grafana: # working without defaults
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      prometheus: # working without defaults
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      kiali:
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      tracing.jaeger.elasticsearch:
        container:
          resources:
            requests:
              cpu: '1'
              memory: 4Gi
            limits:
              cpu: '1'
              memory: 4Gi
      tracing.jaeger.collector:
        container:
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
    defaults: # merged into any component specific overrides. component specific overrides take precedence
      container:
        resources: {} # opting to use LimitRange instead since oauth sidecars don't get the defaults
  gateways:
    enabled: true
    egress:
      enabled: false
    ingress: 
      enabled: false
    additionalIngress:
      sso-ingressgateway: # SSO ingress
        enabled: true
        service:
          type: ClusterIP
          metadata:
            labels:
              istio: ingressgateway
              app: sso-ingressgateway
      nonsso-ingressgateway:
        enabled: true
        services: 
          type: ClusterIP
          metadata:
            labels:
              istio: nonsso-ingressgateway
              app: nonsso-ingressgateway
    openshiftRoute:
      enabled: false
  tracing:
    # change to None to disable tracing
    type: Jaeger
  addons:
    jaeger:
      name: jaeger
      install:
        storage: 
          type: Elasticsearch 
          elasticsearch:
            indexCleaner:
              enabled: true
              numberOfDays: 2
              schedule: "55 23 * * *"
            nodeCount: 2
            redundancyPolicy: "SingleRedundancy"
            storage: 
              storageClassName: gp2
              size: 50Gi
            # resource requests/limits specified in spec.runtime
    grafana:
      enabled: true
      install: {}
    kiali:
      name: kiali
      enabled: true
      # we want maistra to create the kiali resource
      install: {}
    prometheus:
      enabled: true

