apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sso-api
spec:
  port:
    targetPort: http2
  tls:
    termination: edge
  to:
    kind: Service
    name: sso-ingressgateway
    weight: 100
  wildcardPolicy: None